### ISSUE TITLE
[MCOMPILER-39] compiler:compile with fork fails on Windows

### ISSUE THREAD

**Issue by olamy** [olamy/maven-compiler-plugin#146]
**[Jeremie Poutrin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lapoutre)** opened **[MCOMPILER-39](https://issues.apache.org/jira/browse/MCOMPILER-39?redirect=false)** and commented

\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-compiler-plugin\</artifactId>
\<configuration>
\<fork>true\</fork>
\<source>1.4\</source>
\<target>1.4\</target>
\</configuration>
\</plugin>

...
[INFO] [compiler:compile]
Compiling 412 source files to d:\java\CVS-Projects\project\core\target\classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Fatal error compiling

Embedded error: Error while executing the external compiler.
CreateProcess: CMD.EXE /X /C javac -d d:\java\CVS-Projects\project\target\classes -classpath "$CLASSPATH" src.java src2.java ...

If I'm not wrong, On windows CMD.exe can only recieve 256 characters.
And maybe could be better to call directly javac with the createProcess method.

---

**Affects:** 2.0.1

**Issue Links:**
- [MCOMPILER-22](https://issues.apache.org/jira/browse/MCOMPILER-22) Compilation fails: "The command line is too long."
 (_**"duplicates"**_)

**Comment by olamy** [comment]
**[Jeremie Poutrin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lapoutre)** commented

maybe it'd be easier with the stack trace :

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Fatal error compiling
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:488)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:111)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
Caused by: org.codehaus.plexus.compiler.CompilerException: Error while executing the external compiler.
at org.codehaus.plexus.compiler.javac.JavacCompiler.compileOutOfProcess(JavacCompiler.java:330)
at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:132)
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:483)
... 19 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:697)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:74)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:60)
at org.codehaus.plexus.compiler.javac.JavacCompiler.compileOutOfProcess(JavacCompiler.java:324)
... 21 more
Caused by: java.io.IOException: CreateProcess: CMD.EXE /X /C javac -d d:\java\CVS-Projects\project\target\classes -classpath "$CLASSPATH" src.java src2.java ...

at java.lang.Win32Process.create(Native Method)
at java.lang.Win32Process.\<init>(Win32Process.java:66)
at java.lang.Runtime.execInternal(Native Method)
at java.lang.Runtime.exec(Runtime.java:566)
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:692)
... 24 more

**Comment by olamy** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

If it's the lenght problem, it's already in MCOMPILER-22
