### ISSUE TITLE
[MCOMPILER-346] workaround to jdk bug: assertionError inside javac when using javax.tools API

### ISSUE THREAD

**Issue by olamy** [olamy/maven-compiler-plugin#332]
**[Tobias Gierke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tgierke2342)** opened **[MCOMPILER-346](https://issues.apache.org/jira/browse/MCOMPILER-346?redirect=false)** and commented

Maven 3.5.3, 64-bit linux, Oracle JDK 10.0.1

Compilation fails with a crash  inside javac **unless** the maven-compiler-plugin is configured with

```java
<forceJavacCompilerUse>true</forceJavacCompilerUse>
```

I had a brief look at the sources of Modules.java in the current OpenJDK10 and it looks like this is the assertion that gets tripped (line numbers do not match exactly but it's close enough):

```java
    public boolean enter(List<JCCompilationUnit> trees, ClassSymbol c) {
        Assert.check(rootModules != null || inInitModules || !allowModules);
        return enter(trees, modules -> {}, c);
    }
```

Since the crash does not happen when invoking the compiler using commandline arguments I suspect the plugin does something unexpected with the javax.tools JavaCompiler API that later trips the exception.

Unfortunately this is a commercial project so I cannot provide a test case :( The project itself is a JDK8 project we're currently migrating to JDK10 and while the project itself has no module-info files some of our dependencies do (at least Automatic-Module-Name gets set in their manifests).

I'll attach the output of a compile run with the '-verbose' option to this ticket.

Plugin configuration:

```java
<build>
  <plugins>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          <configuration>
            <source>10</source>
            <target>10</target>
            <release>10</release>
            <!-- <forceJavacCompilerUse>true</forceJavacCompilerUse> -->
            <compilerArgs>
                <arg>-Werror</arg>
                <arg>-verbose</arg>
            </compilerArgs>
          </configuration>
        </plugin>
  </plugins>
</build>
```

Exception:

```java
Exception in thread "main" java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:244)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:829)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1506)
        at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
        at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1308)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1139)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1065)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:992)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:197)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:165)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:183)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:165)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:771)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1075)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

---

**Affects:** 3.7.0

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12929570/log.txt) (_1.02 MB_)
- [sample_project.tgz](https://issues.apache.org/jira/secure/attachment/12929604/sample_project.tgz) (_4.13 kB_)

**Remote Links:**
- [MCOMPILER-346 Minimal Reproducible Example (MRE)
](https://github.com/basil/MCOMPILER-346-mre)

6 votes, 17 watchers

**Comment by olamy** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you create an example project which shows the problem?

**Comment by olamy** [comment]
**[Tobias Gierke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tgierke2342)** commented

You're lucky , the affected module only contained 63 source files so I was able to narrow this one down (see attached sample project). The crash seems to be related to something in the pom XML. While incrementally removing stuff from the pom.xml I noticed that the crash went away (and instead I just got an - expected - compilation error).

**Comment by olamy** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

The first thing I get is the following warning by using `mvn clean`

```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.voipfuture.testproject:testproject:jar:1.2.15-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 1046, column 24
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

Furthermore I get:

```
[WARNING] The POM for org.springframework:spring-jdbc:jar:4.1.6.RELEASE_patched2 is missing, no dependency information available
```

Why is the maven-reactor-plugin in the plugin list? This does not make sense...
Apart from that you are mixing versions of maven-surefire/maven-failsafe ..why add a dependency to surefire junit-47 which is usually not needed..
An explude for `*IT.java` in maven-surefire-plugin is not needed cause it's default...

BTW: Is this pom file in the test project your real hand crafted one ? It does not look like so?

**Comment by olamy** [comment]
**[Jason](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jasoncodesaway)** commented

[Tobias Gierke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tgierke2342) A sincere and heartfelt thank you for posting this! I spent days trying to find the javac issues, your 'forceJavacCompilerUser' took me back out of the stone age and illuminated all the issues. Thank you from Florida!

**Comment by olamy** [comment]
**[Tobias Gierke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tgierke)** commented

[jasonCodesAway](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jasonCodesAway) Thanks for the kind words !

[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise) Like I said, this is a test-case I created by elimination from a commercial project with ~700 kLOC of Java code and 43 pom.xml files with ~6 kLOC. The pom.xml was created by combining individual files and then incrementally removing things as long as the crash continue to happen. I already spend quite some time to arrive at this somewhat minimal test-case, so this is as good as it gets. I really don't see how any of the warnings justify a crash/triggered assertion though. Were you able to reproduce the crash with the attached sample project ?

**Comment by olamy** [comment]
**[Marek Šabo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zeratul)** commented

Can confirm the issue is happening in my project too: Maven 3.6.1 and Maven 3.3.9 using OpenJDK 11.0.2.

After upgrading a Flexmark library that changed, I'd see following message only by using enabling **forceJavacCompilerUse:**
 

```java
[ERROR] ...../backend/view/MarkdownHtmlView.java:[9,32] error: cannot find symbol
 symbol: class IParse
 location: package com.vladsch.flexmark.util
```

Without it, I could only see this stacktrace:

```java
Exception in thread "main" java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:247)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:837)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1521)
        at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
        at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

```

**Comment by olamy** [comment]
**[ffather](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ffatheranderson@gmail.com)** commented

Faced the same issue. Using the WSL2 and next versions of maven and java:

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /mnt/c/dev/apache-maven-3.8.1
Java version: 11.0.6, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-19041-microsoft", arch: "amd64", family: "unix"

**Comment by olamy** [comment]
**[Andrei Rebegea](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=andrei.rebegea)** commented

How do I upvote this defect to be fixed ? It is embarrassing...

D:\proj>mvn --version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: D:\maven
Java version: 11.0.12, vendor: Eclipse Foundation, runtime: D:\openJDK11
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

D:\proj>java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

**Comment by olamy** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

I have run into this bug repeatedly while working on Jenkins. I created a [Minimal Reproducible Example (MRE)](https://github.com/basil/MCOMPILER-346-mre).

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Ok there might be some error message report when looking at diagnostic here https://github.com/codehaus-plexus/plexus-compiler/blob/88562f744be32359d8cb3c4ce584439061ada74b/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavaxToolsCompiler.java#L137

 

[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil) thanks to provide an example project. Can you please add some license on it (such Apache) otherwise I cannot import it here thanks

**Comment by olamy** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

> Can you please add some license on it (such Apache) otherwise I cannot import it here thanks

Sure, I added an Apache license file.

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

for reference the root cause is https://bugs.openjdk.java.net/browse/JDK-8210649

but need a workaround in plexus-compiler-javac

related plexus-compiler PR https://github.com/codehaus-plexus/plexus-compiler/pull/196

**Comment by olamy** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

> for reference the root cause is https://bugs.openjdk.java.net/browse/JDK-8210649

Backport PR: [openjdk/jdk11u-dev#855](https://github.com/openjdk/jdk11u-dev/pull/855)

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

few workaround until next release of compiler plugin.

override plexus-compiler version

      \<plugin>

        \<groupId>org.apache.maven.plugins\</groupId>

        \<artifactId>maven-compiler-plugin\</artifactId>

        \<version>3.10.0\</version>

        \<configuration>

          \<release>11\</release>

        \</configuration>

        \<dependencies>

          \<dependency>

            \<groupId>org.codehaus.plexus\</groupId>

            \<artifactId>plexus-compiler-api\</artifactId>

            \<version>2.11.0\</version>

          \</dependency>

          \<dependency>

            \<groupId>org.codehaus.plexus\</groupId>

            \<artifactId>plexus-compiler-javac\</artifactId>

            \<version>2.11.0\</version>

          \</dependency>

        \</dependencies>

      \</plugin>

 

use jdk 17 

or having code compiling :P

**Comment by olamy** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy) Both this issue (tracking [JDK-8210649](https://bugs.openjdk.java.net/browse/JDK-8210649)) and MCOMPILER-415 (tracking [JDK-8216202](https://bugs.openjdk.java.net/browse/JDK-8216202)) are resolved for me by backporting [openjdk/jdk@`{}44ae643b2b4{`}](https://github.com/openjdk/jdk/commit/44ae643b2b49b66b1fff4c151c17972c6b683cc0) to `jdk11u-dev` as in [openjdk/jdk11u-dev#919](https://github.com/openjdk/jdk11u-dev/pull/919) (tested locally against `jenkinsci/acceptance-test-harness`).

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil) awesome! thanks for looking after this.
good luck to get fixes backported in jdk11 ;)

**Comment by olamy** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

The fix for the underlying OpenJDK issue has been backported to `jdk11u-dev` in [openjdk/jdk11u-dev#919](https://github.com/openjdk/jdk11u-dev/pull/919) toward OpenJDK 11.0.16, currently scheduled for a July 2022 GA.
