### ISSUE TITLE
[MCOMPILER-480] Running om macOS Monterey produces an error

### ISSUE THREAD

**Issue by olamy** [olamy/maven-compiler-plugin#390]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** opened **[MCOMPILER-480](https://issues.apache.org/jira/browse/MCOMPILER-480?redirect=false)** and commented

We get the following error building our project with MCP 3.9.0 on 12.1 Morterey macOS (verified on 2 other machines).
Running on maven 3.8.3 and 3.8.4.

The problem disappears when downgrading to 3.8.1. We haven't observed this issue on ubuntu os neither windows machines. 

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:testCompile (default-testCompile) on project dokgen: Error while storing the mojo status: Input length = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:testCompile (default-testCompile) on project fp-dokgen: Error while storing the mojo status
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while storing the mojo status
    at org.apache.maven.shared.incremental.IncrementalBuildHelper.afterRebuildExecution (IncrementalBuildHelper.java:338)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1191)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:175)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
    at java.nio.charset.CoderResult.throwException (CoderResult.java:275)
    at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:306)
    at sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:281)
    at sun.nio.cs.StreamEncoder.write (StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write (OutputStreamWriter.java:211)
    at java.io.BufferedWriter.flushBuffer (BufferedWriter.java:120)
    at java.io.BufferedWriter.close (BufferedWriter.java:268)
    at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray (FileUtils.java:466)
    at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray (FileUtils.java:437)
    at org.apache.maven.shared.incremental.IncrementalBuildHelper.afterRebuildExecution (IncrementalBuildHelper.java:334)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1191)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:175)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
 
```

---

**Affects:** 3.9.0

0 votes, 5 watchers

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please try each Maven version between 3.8.1 and 3.8.4 and identify which is the first one failing.

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

Verified. The same error om 3.8.1 and 3.8.2. It is clearly MCP 3.9.0 related because it works with version 3.8.1 with all maven versions.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Then I would recommend to bisect those Maven versions. When this is found bisect this plugin also. I can't do because I don't have access to that OS.

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

 
Verified.

|Maven version|MCP version|Build status |
|:---|:---|:---|
|3.8.1 |3.8.1|OK|
|3.8.2|3.8.1|OK|
|3.8.3|3.8.1|OK|
|3.8.4|3.8.1|OK|
|3.8.1 |3.9.0|Error|
|3.8.2|3.9.0|Error|
|3.8.3|3.9.0|Error|
|3.8.4|3.9.0|Error|

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

So I guess the release if faulty. The next step is to fetch MCOMPILER from GitHub and perform a `git bisect` betweeen 3.8.1 and 3.9.0. You should pretty fast be able to find the offending commeit. Then we will see what we need to handle.

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

Hi, just took the bisect and it turns out that the error was introduced with this commit:

```java
1f0f0168eb10bfdad131b32d1286e909273cf383 is the first bad commit
commit 1f0f0168eb10bfdad131b32d1286e909273cf383
Author: Sylwester Lachiewicz <slachiewicz@apache.org>
Date:   Mon May 3 08:20:15 2021 +0200    Bump maven-shared-utils from 3.2.1 to 3.3.4
 
```

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This is very good. So now you need to use the MCP 3.8.1, update maven-shared-utils version by version to narrow down the offending version. Then we can narrow down the cause.

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

Done - 3.2.1 is ok - everything above causes the error.

Lot of things happened between 02.2018 - release of 3.2.1 and 06.2020 - release of 3.3.3

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

Just narrowed down the maven-shared-utils to this commit:

```java
e57180309a64758e161513d80f1185e13dc84826 is the first bad commit
commit e57180309a64758e161513d80f1185e13dc84826
Author: Rob Oxspring <roxspring@imapmail.org>
Date:   Fri May 1 00:35:56 2020 +0100    [MSHARED-884] - Add tests for existing FileUtils.copyFile() method with no filtering.
    
    - Add tests for existing FileUtils.copyFile() method with filtering.
    - Refactor to deal with the simpler no-filters case first
    - Only overwrite existing file if there's a content change
    - Avoid conflicts with Java 9 additional Buffer methods
    - Consistent explicit use of Charset instances
    - Prefer Files.newBufferedReader/Writer methods
    - Use TimeUnit rather than constants in millisecond 
```

https://github.com/apache/maven-shared-utils/commit/e57180309a64758e161513d80f1185e13dc84826

**Comment by olamy** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

[mrsladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mrsladek) - Can you provide example minimal project in zip or public repo which show of such error. 

On my test project - I can't reproduce error

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 17.0.2, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.0.1", arch: "x86_64", family: "mac"

...
[INFO] --- maven-compiler-plugin:3.9.0:compile (default-compile) @ test ---
...
[INFO] --- maven-compiler-plugin:3.9.0:testCompile (default-testCompile) @ test ---
...
[INFO] BUILD SUCCESS
```

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Interesting...I guess the use of NIO2 with charset mappers causes an issue. Can you run the build in verbose mode and may identify the file in question? If not, alternatively with `truss` for open, fopen, openat for the last opened file and there should be an fwrite: https://stackoverflow.com/q/31045575/696632

**Comment by olamy** [comment]
**[Michal Sladek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER283708)** commented

[sjaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sjaranowski) just created this one https://github.com/mrsladek/MCOMPILER-480

It is getting interesting because it fails only when I run the maven install from the terminal in intellij. When I run it directly from the macos terminal it works fine.

The funny thing is that on both places it uses the same maven installation and configuration:

```java
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 17, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: nb_NO, platform encoding: UTF-8
OS name: "mac os x", version: "11.2", arch: "x86_64", family: "mac" 
```

Taking [this](https://github.com/mrsladek/MCOMPILER-480/blob/da7e9da6a75e7dfe191fe95417927a9f8cd75792/pom.xml#L87) comment out will make it work in intellij too.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Could this be a race condition with Maven and IntelliJ? If it works with plain Maven then it is likely an IntelliJ issue?

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

using osx everyday and running mvn from console I never have any issue.

Should reported to IntelliJ folks or please give us something to reproduce.

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

closing as "cannot reproduce"

if you have more details please reopen it.

**Comment by olamy** [comment]
**[Vasiliy Kudriavtsev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dunemaster)** commented

I am getting the same problem, but on Windows (with russian locale)

Downgrading to MCP 3.8.1 makes the problem go away

 

[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ snakeyaml ---
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-compiler-plugin:3.10.1, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5a2e4553]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile' with basic configurator -->[DEBUG]   (f) basedir = c:\dev\snakeyaml
[DEBUG]   (f) buildDirectory = c:\dev\snakeyaml\target
[DEBUG]   (f) compileSourceRoots = [c:\dev\snakeyaml\src\test\java]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) createMissingPackageInfoClass = true
[DEBUG]   (f) debug = true
[DEBUG]   (f) debugFileName = javac-test
[DEBUG]   (f) enablePreview = false
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) failOnWarning = false
[DEBUG]   (f) forceJavacCompilerUse = false
[DEBUG]   (f) fork = false
[DEBUG]   (f) generatedTestSourcesDirectory = c:\dev\snakeyaml\target\generated-test-sources\test-annotations
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile {execution: default-testCompile}
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory = c:\dev\snakeyaml\target\test-classes
[DEBUG]   (f) parameters = false
[DEBUG]   (f) project = MavenProject: org.yaml:snakeyaml:1.34-SNAPSHOT @ c:\dev\snakeyaml\pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6bf570c
[DEBUG]   (f) showDeprecation = false
[DEBUG]   (f) showWarnings = false
[DEBUG]   (f) skipMultiThreadWarning = false
[DEBUG]   (f) source = 7
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (s) target = 7
[DEBUG]   (f) testPath = [c:\dev\snakeyaml\target\test-classes, c:\dev\snakeyaml\target\classes, C:\m2repo\repository\junit\junit\4.13.2\junit-4.13.2.jar, C:\m2repo\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar, C:\m2repo\repository\org\apache\velocity\velocity-engine-core\2.3\velocity-engine-core-2.3.jar, C:\m2repo\repository\org\apache\commons\commons-lang3\3.11\commons-lang3-3.11.jar, C:\m2repo\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar, C:\m2repo\repository\joda-time\joda-time\2.11.1\joda-time-2.11.1.jar, C:\m2repo\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar]
[DEBUG]   (f) testSource = 8
[DEBUG]   (f) testTarget = 8
[DEBUG]   (f) useIncrementalCompilation = true
[DEBUG]   (f) verbose = false
[DEBUG]   - end configuration --
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding c:\dev\snakeyaml\target\generated-test-sources\test-annotations to test-compile source roots:
  c:\dev\snakeyaml\src\test\java
[DEBUG] New test-compile source roots:
  c:\dev\snakeyaml\src\test\java
  c:\dev\snakeyaml\target\generated-test-sources\test-annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[DEBUG] New dependency detected: c:\dev\snakeyaml\target\classes
[INFO] Changes detected - recompiling the module!
[DEBUG] Classpath:
[DEBUG]  c:\dev\snakeyaml\target\test-classes
[DEBUG]  c:\dev\snakeyaml\target\classes
[DEBUG]  C:\m2repo\repository\junit\junit\4.13.2\junit-4.13.2.jar
[DEBUG]  C:\m2repo\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar
[DEBUG]  C:\m2repo\repository\org\apache\velocity\velocity-engine-core\2.3\velocity-engine-core-2.3.jar
[DEBUG]  C:\m2repo\repository\org\apache\commons\commons-lang3\3.11\commons-lang3-3.11.jar
[DEBUG]  C:\m2repo\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar
[DEBUG]  C:\m2repo\repository\joda-time\joda-time\2.11.1\joda-time-2.11.1.jar
[DEBUG]  C:\m2repo\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar
[DEBUG] Source roots:
[DEBUG]  c:\dev\snakeyaml\src\test\java
[DEBUG]  c:\dev\snakeyaml\target\generated-test-sources\test-annotations
[DEBUG] Command line options:
[DEBUG] -d c:\dev\snakeyaml\target\test-classes -classpath c:\dev\snakeyaml\target\test-classes;c:\dev\snakeyaml\target\classes;C:\m2repo\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\m2repo\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\m2repo\repository\org\apache\velocity\velocity-engine-core\2.3\velocity-engine-core-2.3.jar;C:\m2repo\repository\org\apache\commons\commons-lang3\3.11\commons-lang3-3.11.jar;C:\m2repo\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\m2repo\repository\joda-time\joda-time\2.11.1\joda-time-2.11.1.jar;C:\m2repo\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar; -sourcepath c:\dev\snakeyaml\src\test\java;c:\dev\snakeyaml\target\generated-test-sources\test-annotations; -s c:\dev\snakeyaml\target\generated-test-sources\test-annotations -g -nowarn -target 8 -source 8 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 513 source files to c:\dev\snakeyaml\target\test-classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.582 s
[INFO] Finished at: 2022-10-22T11:54:03+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project snakeyaml: Error while storing the mojo status: Input length = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project snakeyaml: Error while storing the mojo status
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while storing the mojo status
        at org.apache.maven.shared.incremental.IncrementalBuildHelper.afterRebuildExecution(IncrementalBuildHelper.java:338)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1244)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:183)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        ... 20 common frames omitted
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:306)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:208)
        at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
        at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
        at java.base/java.io.Writer.write(Writer.java:249)
        at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray(FileUtils.java:460)
        at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray(FileUtils.java:437)
        at org.apache.maven.shared.incremental.IncrementalBuildHelper.afterRebuildExecution(IncrementalBuildHelper.java:334)
        ... 24 common frames omitted
        Suppressed: java.nio.charset.UnmappableCharacterException: Input length = 1
                at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
                at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:306)
                at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
                at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
                at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:208)
                at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
                at java.base/java.io.BufferedWriter.close(BufferedWriter.java:268)
                at org.apache.maven.shared.utils.io.FileUtils.fileWriteArray(FileUtils.java:466)
                ... 26 common frames omitted
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Dunemaster](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Dunemaster), do you think you could trace down the content it is trying to write or the encoding in question?

**Comment by olamy** [comment]
**[Vasiliy Kudriavtsev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dunemaster)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) , is there a way other then rebuilding the plugin and adding debug output?

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Dunemaster](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Dunemaster), no.
